MA-16453 Fix build error in android-r-preview-1
Meet below build error:
error: vendor/nxp-opensource/imx/display/display/Android.bp:18:1: module
"libionallocator" variant "android_vendor.R_arm64_armv8-a_cortex-a53_static":
source path "system/core/libion/include" does not exist

vendor/nxp-opensource/imx/display/display/IonAllocator.cpp:23:10: fatal error:
'ion_4.12.h' file not found

system/core/libion has been moved to system/memory folder.
Here change to correct path.

Change-Id: I041f43bd68051914b0b812682699fe4e3e93572a
Signed-off-by: Jessie Hao <juan.hao@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/11424
Reviewed-by: guoyin.chen <guoyin.chen@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/12000