MA-17629 fix Android Auto emulator build error
Moved some build configs for libimxcamerahwl_impl by arm64 only due we
have below build error when build emulator:
[100% 2/2] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l
out/.module_paths/Android.bp.list -b out/soong -n out -d
out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja
-o out/soong/build.ninja Android.bp
error: vendor/nxp-opensource/imx/camera/Android.bp:23:1: module
"libimxcamerahwl_impl" variant "android_vendor.30_x86_64_shared":
depends on disabled module "libfsldisplay"
error: vendor/nxp-opensource/imx/camera/Android.bp:23:1: module
"libimxcamerahwl_impl" variant "android_vendor.30_x86_64_shared":
depends on disabled module "libfsldisplay"
22:22:22 soong bootstrap failed with: exit status 1

TEST: make sdk sdk_repo

Change-Id: Ib7f0879ad053a6e2002421f605b51ad3aadc7672
Signed-off-by: Haoran.Wang <elven.wang@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/13668
Reviewed-by: guoyin.chen <guoyin.chen@nxp.com>