MA-17121-3 Fix build error for gtest
Fixed below build error due Android R-fs code base upgrade:

error: vendor/nxp-opensource/imx/gtest/Android.bp:52:1: module
"security_unit_test" variant "android_arm_armv7-a-neon_cortex-a9":
depends on //external/boringssl:l ibcrypto_static which is not
visible to this module

Change-Id: Ia1b302eaa93f7eea7bc18f148d91ca04f220fc5b
Signed-off-by: Haoran.Wang <elven.wang@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/12578
Reviewed-by: Zhai.He <zhai.he@nxp.com>