MA-19531 [Android] fix build error for camera hal
SubmitRequests definition have been changed in CameraDeviceSessionHwl.
Align the definition with google.
error 1:
vendor/nxp-opensource/imx/camera/CameraDeviceSessionHWLImpl.h:138:58:
error: non-virtual member function marked 'override' hides virtual
member function
const std::vector<HwlPipelineRequest>& requests) override;
^

include libui which include libmath_header
error 2:
In file included from vendor/nxp-opensource/imx/camera/ImageProcess.cpp:24:
In file included from vendor/nxp-opensource/imx/display/display/Composer.h:23:
In file included from vendor/nxp-opensource/imx/display/display/Layer.h:21:
frameworks/native/include/ui/Rect.h:27:10: fatal error: 'math/HashCombine.h' file not found
         ^~~~~~~~~~~~~~~~~~~~

Change-Id: I27ecfb92ced744039ec43faa948edaf8fd7811e5
Signed-off-by: zhang sanshan <pete.zhang@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/17161
Reviewed-by: Tian Yang <yang.tian@nxp.com>