MA-16983 Fix build error for r-fs
1. Fix build error for removing deps of libhidltransport and libhwbinder due Google combine them
into libhidlbase:
error: vendor/nxp-opensource/imx/dumpstate/Android.bp:17:1: module
"android.hardware.dumpstate@1.0-service.imx" variant
"android_vendor.R_arm64_armv8-a_cortex-a53"
: depends on //system/libhidl:libhidltransport which is not visible to
this module
error: vendor/nxp-opensource/imx/dumpstate/Android.bp:17:1: module
"android.hardware.dumpstate@1.0-service.imx" variant
"android_vendor.R_arm64_armv8-a_cortex-a53"
: depends on //system/libhwbinder:libhwbinder which is not visible to
this module

2. Fix header path for display HALs:
vendor/nxp-opensource/imx/display/display/android/Region.cpp:32:10:
fatal error: 'private/ui/RegionHelper.h' file not found

3. Fixed deps error of libperfmgr for power HALs:
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l
out/.module_paths/Android.bp.list -b out/soong -n out -d
out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-gl
obs.ninja -o out/soong/build.ninja Android.bp
error: vendor/nxp-opensource/imx/power/Android.bp:22:1:
"android.hardware.power@1.3-service.imx" depends on undefined module
"libperfmgr"
Module "android.hardware.power@1.3-service.imx" is defined in namespace
"." which can read these 1 namespaces: ["."]
Module "libperfmgr" can be found in these namespaces:
["hardware/google/pixel"]

Change-Id: I2c8f0718505e55181b1d2163a720e66b7d7aa5a7
Signed-off-by: Haoran.Wang <elven.wang@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/12002
Reviewed-by: guoyin.chen <guoyin.chen@nxp.com>