MA-21771-1 Add android.hardware.neuralnetworks-shell-service-imx
This add and enable android.hardware.neuralnetworks-shell-service-imx.
Reference:
config/android.hardware.neuralnetworks-shell-service-sample.rc
config/android.hardware.neuralnetworks-shell-service-sample.xml

Remove the updatable-via-apex to fix the below build error:
All HALs in device manifest are declared in FCM <= level 8
ERROR: files are incompatible: Device manifest and framework
compatibility matrix are incompatible: APEX-implemented HALs not
supported in compatibility matrix:

This change devicesToRegister to vsi-device-0,nnapi-imx_sl.

Change-Id: I2f93027a327b65b324e42d7c582b5eb41eec8425
Signed-off-by: Jessie Hao <juan.hao@nxp.com>
Reviewed-on: http://androidsource.nxp.com/project/23049
Reviewed-by: Xuegang Liu <xuegang.liu@nxp.com>