MA-17121-4 Fix build error of gtest
vendor/nxp-opensource/imx/gtest/keymaster_hidl_hal_test.cpp:23:10: fatal
error: 'openssl/evp.h' file not found
error: vendor/nxp-opensource/imx/gtest/Android.bp:69:1: module
"security_unit_test" variant "android_arm_armv7-a-neon_cortex-a9":
depends on //external/boringssl:libcrypto_static which is not visible to
this module

Change-Id: Ia26e77f14ae05b42b0bc8b6d00418471bd2d8936
Signed-off-by: zhai.he <zhai.he@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/12688
Reviewed-by: ji.luo <ji.luo@nxp.com>