MA-12647 [Android] enable BOARD_HAVE_IMX_EVS which support evs hal
it will have below error when compile evk_8mm.
error: android.hardware.automotive.evs@1.0-EvsEnumeratorHw
(EXECUTABLES android-arm64) missing libopencl-2d (SHARED_LIBRARIES android-arm64)

It do not compile android.hardware.automotive.evs@1.0-EvsEnumeratorHw,
however it still check the dependecy of this module.
Build evs hal when only define BOARD_HAVE_IMX_EVS.

Change-Id: I77be9c69955b79341acb313019a7094ba1e80f5f
Signed-off-by: zhang sanshan <sanshan.zhang@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/5902
Reviewed-by: guoyin.chen <guoyin.chen@nxp.com>