MA-18061 [Android 11] BurstCaptureTest#testYuvBurstWithStillBokeh failed
The test failed due to ANDROID_CONTROL_AE_LOCK_AVAILABLE is not added.
Add camera.go to define ANDROID_SDK_VERSION, so the code to add
related tags will be compiled.

It will fix about 12 tests failed as
junit.framework.AssertionFailedError: The static info key
'android.control.aeLockAvailable' was null

Change-Id: Ieff6fbd68faf501209b2176c7137b0b2ef97ba33
Signed-off-by: fang hui <hui.fang@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/13806
Reviewed-by: zhang sanshan <sanshan.zhang@nxp.com>