MA-11592 Build error on imx.git with android-p-review-1 tag
Fix the build error as below:
Memory.cpp:34:5: error: use of undeclared identifier 'memset'
IonManager.cpp:132:36: error: use of undeclared identifier 'strerror'
Region.cpp:581: error: undefined reference to 'android::CallStack::CallStack()'

CallStack is defined in libutilscallstack.so which is not vendor available
in Android P

Change-Id: Iecdf93be70312c04e7a1adb2f67aabbc7417a1d4
Signed-off-by: guoyin.chen <guoyin.chen@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/4238
Reviewed-by: Xiaowen Liu <xiaowen.liu@nxp.com>