MA-19178 Disable camera when it is not imx BOARD_PLATFORM
Meet below build error when lunch aosp_arm64-user.

error: vendor/nxp-opensource/imx/camera/Android.bp:107:1: module
"libimxcamerahwl_impl" variant "android_vendor.S_arm64_armv8-a_shared":
depends on disabled module "libfsldisplay"

Should disable "libimxcamerahwl_impl" module if its BOARD_PLATFORM not imx.

Signed-off-by: Jessie Hao <juan.hao@nxp.com>
Change-Id: I8c226510da75d1b0557999133e08965d16302b8f
Reviewed-on: http://androidsource.ap.freescale.net/project/16155
Reviewed-by: zhang sanshan <sanshan.zhang@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/16565
Reviewed-on: http://androidsource.ap.freescale.net/project/16599